title: Matthew Walton
description: Aikido, music, dance, cats, programming
remote_theme: fongandrew/jekyll-theme-hydeout
paginate:         5

plugins_dir:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

gems: [jekyll-paginate, jekyll-feed]
